version: '3.7'
services:
  backend:
    image: node:12
    platform: linux/arm64
    environment:
        - DEBUG=app:*
    tty: true
    ports:
        - 3000:3000
        - 5555:5555
    volumes:
        - ../backend:/app
    working_dir: /app
  prisma-db:
    container_name: prisma-db
    image: postgres:12
    ports:
      - "5403:5432"
    volumes:
      - prisma-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
  prisma-test-db:
    container_name: prisma-test-db
    image: postgres:12
    ports:
      - "5402:5432"
    volumes:
      - prisma-test-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

volumes:
  prisma-store:
    driver: local
  prisma-test-store:
    driver: local
